In [173]:
import pandas as pd

In [174]:
plantgen = pd.read_csv('/Users/noshintasnim/Downloads/Solar-Energy-Yield-Predictor/Raw Data/Plant_Generation_&_Weather_censor_Data/Plant_2_Generation_Data.csv')
plantweather = pd.read_csv('/Users/noshintasnim/Downloads/Solar-Energy-Yield-Predictor/Raw Data/Plant_Generation_&_Weather_censor_Data/Plant_2_Weather_Sensor_Data.csv')

In [175]:
plantgen.iloc[72:92]

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
72,2020-05-15 00:45:00,4136001,LlT2YUhhzqhg5Sw,0.0,0.0,0.0,2.825928e+08
73,2020-05-15 00:45:00,4136001,Mx2yZCDsyf6DPfv,0.0,0.0,0.0,2.453646e+06
74,2020-05-15 00:45:00,4136001,NgDl19wMapZy17u,0.0,0.0,0.0,1.115126e+08
75,2020-05-15 00:45:00,4136001,PeE6FRyGXUgsRhN,0.0,0.0,0.0,1.348351e+09
76,2020-05-15 00:45:00,4136001,Qf4GUc1pJu5T6c6,0.0,0.0,0.0,8.384214e+08
77,2020-05-15 00:45:00,4136001,Quc1TzYxW2pYoWX,0.0,0.0,5495.0,3.295091e+08
78,2020-05-15 00:45:00,4136001,V94E5Ben1TlhnDV,0.0,0.0,0.0,1.412083e+09
79,2020-05-15 00:45:00,4136001,WcxssY2VbP4hApt,0.0,0.0,0.0,1.816953e+08
80,2020-05-15 00:45:00,4136001,mqwcsP2rE7J0TFp,0.0,0.0,0.0,5.935800e+08
81,2020-05-15 00:45:00,4136001,oZ35aAeoifZaQzV,0.0,0.0,0.0,1.659965e+09
82,2020-05-15 00:45:00,4136001,oZZkBaNadn6DNKz,0.0,0.0,0.0,1.708083e+09
83,2020-05-15 00:45:00,4136001,q49J1IKaHRwDQnt,0.0,0.0,4315.0,3.399230e+05
84,2020-05-15 00:45:00,4136001,rrq4fwE8jgrTyWY,0.0,0.0,0.0,1.209641e+08
85,2020-05-15 00:45:00,4136001,vOuJvMaM2sgwLmb,0.0,0.0,0.0,2.211962e+06
86,2020-05-15 00:45:00,4136001,xMbIugepa2P7lBB,0.0,0.0,9166.0,1.066566e+08
87,2020-05-15 00:45:00,4136001,xoJJ8DcxJEcupym,0.0,0.0,0.0,2.091436e+08
88,2020-05-15 01:00:00,4136001,4UPUqMRk7TRMgml,0.0,0.0,7540.0,2.429011e+06
89,2020-05-15 01:00:00,4136001,81aHJ1q11NBPMrL,0.0,0.0,0.0,1.215279e+09
90,2020-05-15 01:00:00,4136001,9kRcWv60rDACzjR,0.0,0.0,0.0,2.247720e+09
91,2020-05-15 01:00:00,4136001,Et9kgGMDl729KT4,0.0,0.0,0.0,1.704250e+06

In [176]:
plantweather.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,iq8k7ZNt4Mwm3w0,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,iq8k7ZNt4Mwm3w0,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,iq8k7ZNt4Mwm3w0,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,iq8k7ZNt4Mwm3w0,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,iq8k7ZNt4Mwm3w0,26.596148,25.088210,0.0

In [177]:
plantgen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67698 entries, 0 to 67697
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE_TIME    67698 non-null  object
 1   PLANT_ID     67698 non-null  int64
 2   SOURCE_KEY   67698 non-null  object
 3   DC_POWER     67698 non-null  float64
 4   AC_POWER     67698 non-null  float64
 5   DAILY_YIELD  67698 non-null  float64
 6   TOTAL_YIELD  67698 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 3.6+ MB

In [178]:
plantweather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3259 entries, 0 to 3258
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DATE_TIME            3259 non-null   object
 1   PLANT_ID             3259 non-null   int64
 2   SOURCE_KEY           3259 non-null   object
 3   AMBIENT_TEMPERATURE  3259 non-null   float64
 4   MODULE_TEMPERATURE   3259 non-null   float64
 5   IRRADIATION          3259 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 152.9+ KB

In [179]:
plantgen['DATE_TIME'] = pd.to_datetime(plantgen['DATE_TIME'], errors='coerce')
plantweather['DATE_TIME'] = pd.to_datetime(plantweather['DATE_TIME'], errors='coerce')

plantgen['DATE'] = plantgen['DATE_TIME'].dt.date

plantgen = plantgen.sort_values(by=['SOURCE_KEY', 'DATE_TIME'])

plantgen['INTERVAL_ENERGY'] = plantgen['AC_POWER'] * 0.25

plantgen['DAILY_YIELD'] = plantgen.groupby(['SOURCE_KEY','DATE'])['INTERVAL_ENERGY'].cumsum()

plantgen['TOTAL_YIELD'] = plantgen.groupby(['SOURCE_KEY'])['INTERVAL_ENERGY'].cumsum()

plantgen_agg = plantgen.groupby('DATE_TIME').agg({'PLANT_ID': 'first', 'DC_POWER': 'sum', 
                    'AC_POWER': 'sum', 'DAILY_YIELD': 'sum', 'TOTAL_YIELD': 'sum'}).reset_index()
plantgen_agg.iloc[200:220]

,DATE_TIME,PLANT_ID,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
200,2020-05-17 02:15:00,4136001,0.000000,0.000000,0.000000,301422.799286
201,2020-05-17 02:30:00,4136001,0.000000,0.000000,0.000000,301422.799286
202,2020-05-17 02:45:00,4136001,0.000000,0.000000,0.000000,301422.799286
203,2020-05-17 03:00:00,4136001,0.000000,0.000000,0.000000,301422.799286
204,2020-05-17 03:15:00,4136001,0.000000,0.000000,0.000000,301422.799286
205,2020-05-17 03:30:00,4136001,0.000000,0.000000,0.000000,301422.799286
206,2020-05-17 03:45:00,4136001,0.000000,0.000000,0.000000,301422.799286
207,2020-05-17 04:00:00,4136001,0.000000,0.000000,0.000000,301422.799286
208,2020-05-17 04:15:00,4136001,0.000000,0.000000,0.000000,301422.799286
209,2020-05-17 04:30:00,4136001,0.000000,0.000000,0.000000,301422.799286
210,2020-05-17 04:45:00,4136001,0.000000,0.000000,0.000000,301422.799286
211,2020-05-17 05:00:00,4136001,0.000000,0.000000,0.000000,301422.799286
212,2020-05-17 05:15:00,4136001,0.000000,0.000000,0.000000,301422.799286
213,2020-05-17 05:30:00,4136001,0.000000,0.000000,0.000000,301422.799286
214,2020-05-17 05:45:00,4136001,0.000000,0.000000,0.000000,301422.799286
215,2020-05-17 06:00:00,4136001,85.453333,82.420000,20.605000,301443.404286
216,2020-05-17 06:15:00,4136001,530.254286,511.978095,148.599524,301571.398810
217,2020-05-17 06:30:00,4136001,790.055238,763.419048,339.454286,301762.253571
218,2020-05-17 06:45:00,4136001,942.890952,911.571905,567.347262,301990.146548
219,2020-05-17 07:00:00,4136001,1497.988571,1451.499048,930.222024,302353.021310

In [180]:
plantweather.drop(columns=['SOURCE_KEY'], inplace=True)
plantweather.head()

,DATE_TIME,PLANT_ID,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,26.596148,25.088210,0.0

In [181]:
plantdata = pd.merge(plantgen_agg, plantweather, on=['DATE_TIME', 'PLANT_ID'], how='left')
plantdata.head()

,DATE_TIME,PLANT_ID,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,0.0,0.0,0.0,0.0,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,0.0,0.0,0.0,0.0,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,0.0,0.0,0.0,0.0,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,0.0,0.0,0.0,0.0,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,0.0,0.0,0.0,0.0,26.596148,25.088210,0.0

In [182]:
plantdata['DCE'] = (plantdata['DC_POWER'] / plantdata['DC_POWER'].max()).fillna(0)
plantdata['ACE'] = (plantdata['AC_POWER'] / plantdata['AC_POWER'].max()).fillna(0)
plantdata['IE'] = (plantdata['AC_POWER'] / plantdata['DC_POWER'].max()).fillna(0)
plantdata['YI'] = (plantdata['DC_POWER'] / plantdata['IRRADIATION']).fillna(0)
plantdata['IRRADIATION'] = plantdata['IRRADIATION'] * 1000

In [183]:
plantdata.head(10)

,DATE_TIME,PLANT_ID,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,DCE,ACE,IE,YI
0,2020-05-15 00:00:00,4136001,0.0,0.0,0.0,0.0,27.004764,25.060789,0.0,0.0,0.0,0.0,0.0
1,2020-05-15 00:15:00,4136001,0.0,0.0,0.0,0.0,26.880811,24.421869,0.0,0.0,0.0,0.0,0.0
2,2020-05-15 00:30:00,4136001,0.0,0.0,0.0,0.0,26.682055,24.427290,0.0,0.0,0.0,0.0,0.0
3,2020-05-15 00:45:00,4136001,0.0,0.0,0.0,0.0,26.500589,24.420678,0.0,0.0,0.0,0.0,0.0
4,2020-05-15 01:00:00,4136001,0.0,0.0,0.0,0.0,26.596148,25.088210,0.0,0.0,0.0,0.0,0.0
5,2020-05-15 01:15:00,4136001,0.0,0.0,0.0,0.0,26.512740,25.317970,0.0,0.0,0.0,0.0,0.0
6,2020-05-15 01:30:00,4136001,0.0,0.0,0.0,0.0,26.494339,25.217193,0.0,0.0,0.0,0.0,0.0
7,2020-05-15 01:45:00,4136001,0.0,0.0,0.0,0.0,26.420410,25.065062,0.0,0.0,0.0,0.0,0.0
8,2020-05-15 02:00:00,4136001,0.0,0.0,0.0,0.0,26.401946,24.691469,0.0,0.0,0.0,0.0,0.0
9,2020-05-15 02:15:00,4136001,0.0,0.0,0.0,0.0,26.226078,24.559481,0.0,0.0,0.0,0.0,0.0

In [184]:
plantdata = plantdata.rename(columns={'DC_POWER':'DC_POWER(kW)', 'AC_POWER':'AC_POWER(kW)', 'DCE': 'DC_EFFICIENCY', 'ACE': 'AC_EFFICIENCY', 'IE': 'INVERTOR_EFFICIENCY', 
                                      'YI': 'EFFECTIVE_AREA(m²)', 'DAILY_YIELD': 'DAILY_YIELD(kWh)', 'TOTAL_YIELD': 'TOTAL_YIELD(kWh)', 
                                      'AMBIENT_TEMPERATURE': 'AMBIENT_TEMPERATURE(°C)', 'IRRADIATION': 'IRRADIATION(W/m²)', 'MODULE_TEMPERATURE': 'MODULE_TEMPERATURE(°C)'})
plantdata = plantdata[['DATE_TIME', 'PLANT_ID', 'IRRADIATION(W/m²)', 'AMBIENT_TEMPERATURE(°C)', 'MODULE_TEMPERATURE(°C)', 'DC_POWER(kW)','AC_POWER(kW)', 
                        'DC_EFFICIENCY', 'AC_EFFICIENCY', 'INVERTOR_EFFICIENCY', 'EFFECTIVE_AREA(m²)', 'DAILY_YIELD(kWh)', 'TOTAL_YIELD(kWh)']]
plantdata.iloc[20:30]

,DATE_TIME,PLANT_ID,IRRADIATION(W/m²),AMBIENT_TEMPERATURE(°C),MODULE_TEMPERATURE(°C),DC_POWER(kW),AC_POWER(kW),DC_EFFICIENCY,AC_EFFICIENCY,INVERTOR_EFFICIENCY,EFFECTIVE_AREA(m²),DAILY_YIELD(kWh),TOTAL_YIELD(kWh)
20,2020-05-15 05:00:00,4136001,0.000000,25.117599,24.104580,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,2020-05-15 05:15:00,4136001,0.000000,25.091862,23.897232,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,2020-05-15 05:30:00,4136001,0.000000,24.916968,23.839471,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,2020-05-15 05:45:00,4136001,2.838055,24.741274,23.786662,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,2020-05-15 06:00:00,4136001,12.961978,24.742787,24.077230,331.993333,320.433333,0.012467,0.012334,0.012033,25612.860134,80.108333,80.108333
25,2020-05-15 06:15:00,4136001,21.037669,24.763911,24.356189,587.179524,566.977619,0.022049,0.021824,0.021291,27910.864626,221.852738,221.852738
26,2020-05-15 06:30:00,4136001,42.435399,24.786323,24.548886,1284.205714,1243.556190,0.048223,0.047866,0.046697,30262.604914,532.741786,532.741786
27,2020-05-15 06:45:00,4136001,103.495878,25.048245,25.746662,3450.897143,3373.658571,0.129584,0.129857,0.126684,33343.329204,1376.156429,1376.156429
28,2020-05-15 07:00:00,4136001,199.450484,25.673202,28.674707,6733.253333,6614.380000,0.252840,0.254597,0.248376,33759.022338,3029.751429,3029.751429
29,2020-05-15 07:15:00,4136001,317.665026,26.076818,30.725505,8379.640000,8234.446667,0.314663,0.316956,0.309211,26378.856084,5088.363095,5088.363095

In [185]:
plantdata.to_csv('SOLAR_PLANT_DATA(GENERATION_AND_WEATHER).csv', index=False)